### ISSUE TITLE
not able to run it on my laptop

### ISSUE THREAD

**Issue by aoke79** [nadermx/backgroundremover#75]
this is an amazing project, the effect is perfect, and i'd like to use it on my local laptop, but I failed.
the command is very simple for me:
python -m venv venv_back
python.exe -m pip install --upgrade pip
pip3 install torch torchvision torchaudio
pip3 install ffmpeg backgroundremover
when I tried to use it by "backgroundremover -i jan-02.jpg -o x.jpg", it shows below commands:

downloading model [u2net] to C:\Users\lin\.u2net\u2net.pth ...
downloading part 1 of u2net

Traceback (most recent call last):
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\lin\AIGC\venv_back\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\lin\AIGC\venv_back\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\lin\AIGC\venv_back\Scripts\backgroundremover.exe\__main__.py", line 7, in <module>
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\cmd\cli.py", line 239, in main
    remove(
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\bg.py", line 183, in remove
    model = get_model(model_name)
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\bg.py", line 171, in get_model
    return detect.load_model(model_name="u2net")
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\u2net\detect.py", line 55, in load_model
    utilities.download_files_from_github(
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\utilities.py", line 348, in download_files_from_github    part_content = requests.get(url)
  File "C:\lin\AIGC\venv_back\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\lin\AIGC\venv_back\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\lin\AIGC\venv_back\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\lin\AIGC\venv_back\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\lin\AIGC\venv_back\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

when I run it again, I've found below logs:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\lin\AIGC\venv_back\Scripts\backgroundremover.exe\__main__.py", line 7, in <module>
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\cmd\cli.py", line 239, in main
    remove(
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\bg.py", line 183, in remove
    model = get_model(model_name)
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\bg.py", line 171, in get_model
    return detect.load_model(model_name="u2net")
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\u2net\detect.py", line 82, in load_model
    torch.load(
  File "C:\lin\AIGC\venv_back\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\lin\AIGC\venv_back\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

might you please help take a look at that?
thanks very very much!

**Comment by nadermx** [comment]
Perhaps github was/is down? Try again?   That seems like a requests error
off quick look

**Comment by aoke79** [comment]
thanks a lot for your quick response.
I've found an interesting thing. as I've created a virtual enviroment, but the logs showed it still run the system python. might you please know why?
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\lin\AIGC\venv_back\Scripts\backgroundremover.exe\__main__.py", line 7, in <module>
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\cmd\cli.py", line 239, in main
    remove(
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\bg.py", line 183, in remove
    model = get_model(model_name)
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\bg.py", line 171, in get_model
    return detect.load_model(model_name="u2net")
  File "C:\lin\AIGC\venv_back\lib\site-packages\backgroundremover\u2net\detect.py", line 82, in load_model
    torch.load(
  File "C:\lin\AIGC\venv_back\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\lin\AIGC\venv_back\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by nadermx** [comment]
What command are you running?

**Comment by aoke79** [comment]
backgroundremover -i jan-02.jpg -o x.jpg
or
Script\backgroundremover.exe -i jan-02.jpg -o x.jpg

**Comment by nadermx** [comment]
try this (please note the quotes, and the output extension)
`backgroundremover -i "/path/to/image.jpeg" -o "output.png"`

**Comment by aoke79** [comment]
the same error:
I've run it through CPU, not on GPU.

(venv_back) C:\ed\GPT\backgroundremover>backgroundremover -i "YangGongru.png" -o "YangGongru-output-0.png"
YangGongru-output-0.png
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ed\GPT\venv_back\Scripts\backgroundremover.exe\__main__.py", line 7, in <module>
  File "C:\ed\GPT\venv_back\lib\site-packages\backgroundremover\cmd\cli.py", line 239, in main
    remove(
  File "C:\ed\GPT\venv_back\lib\site-packages\backgroundremover\bg.py", line 183, in remove
    model = get_model(model_name)
  File "C:\ed\GPT\venv_back\lib\site-packages\backgroundremover\bg.py", line 171, in get_model
    return detect.load_model(model_name="u2net")
  File "C:\ed\GPT\venv_back\lib\site-packages\backgroundremover\u2net\detect.py", line 82, in load_model
    torch.load(
  File "C:\ed\GPT\venv_back\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\ed\GPT\venv_back\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by aoke79** [comment]
maybe, it lacked the u2net pth file, do you please know where is the default folder, the detect loaded the pth file?
thanks a lot

**Comment by aoke79** [comment]
> maybe, it lacked the u2net pth file, do you please know where is the default folder, the detect loaded the pth file? thanks a lot

Yes, I've confirmed it. Might you please help upload u2.net.pth and u2net_human_seg.pth to server. the github is very not friendly for Chinese users. :(, or please give the link, and I can download it by myself.
thanks a lot,

**Comment by aoke79** [comment]
I've fixed it, thanks very much

**Comment by davidkern13** [comment]
I have same issue how did you fix it ?

**Comment by nadermx** [comment]
Just upgrade your version, should work now  pip install --upgrade
backgroundremover

**Comment by davidkern13** [comment]
Thanks for response.
I try pip install --upgrade backgroundremover and reinstall but i still have the error, I think models its not downloaded and scripts dont find them and throw error. possible to redownload the train models automaticaly ?
this errors I get in console after run this command backgroundremover -i "./image.jpeg" -o "output.png"
and Python version is 3.11.4

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "path\backgroundremover.exe\__main__.py", line 7, in <module>
  File "path\backgroundremover\cmd\cli.py", line 239, in main
    remove(
  File "path\backgroundremover\bg.py", line 183, in remove
    model = get_model(model_name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "path\backgroundremover\bg.py", line 171, in get_model
    return detect.load_model(model_name="u2net")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path\backgroundremover\u2net\detect.py", line 82, in load_model
    torch.load(
  File "path\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 4554729 more bytes. The file might be corrupted.
